/*
 * menu.h
 *
 *  Created on: 26.06.2012
 *      Author: d.sapunov
 */

#ifndef LOCALIZATION_MENU_H_
#define LOCALIZATION_MENU_H_

#include "uns.h"

#if UNS_LANGUAGE == UNS_LANGUAGE_RUSSIAN

	#define LANG_STD_FORM_YES			"Да"
	#define LANG_STD_FORM_NO			"Нет"
	#define LANG_STD_FORM_RETRY			"Снова"
	#define LANG_STD_FORM_ABORT			"Отменить"
	#define LANG_STD_FORM_IGNORE		"Игнорировать"

	#define LANG_MENU_BUTTON_BACK		"Назад"
	#define LANG_MENU_BUTTON_NEXT		"Далее"
	#define LANG_MENU_BUTTON_CANCEL		"Отм."
	#define LANG_MENU_BUTTON_OK			" OK "
	#define LANG_MENU_BUTTON_YES		" Да "
	#define LANG_MENU_BUTTON_NO			" Нет "
	#define LANG_MENU_BUTTON_PRINT		"Печат"
	#define LANG_MENU_BUTTON_STATS		"Стат."
	#define LANG_MENU_BUTTON_CHOOSE		"Выбор"
	#define LANG_MENU_BUTTON_STOP		"Стоп"
	#define LANG_MENU_BUTTON_HANG_UP	"Сброс"
	#define LANG_MENU_BUTTON_ANSWER		"Ответ"
	#define LANG_MENU_BUTTON_EXIT		"Выход"
	#define LANG_MENU_BUTTON_OPTIONS	"Опции"
	#define LANG_MENU_BUTTON_HEX		"[HEX]"
	#define LANG_MENU_BUTTON_TXT		"[TXT]"

	#define LANG_MENU_BOOK_SETTINGS		"ГЛАВНОЕ МЕНЮ"
	#define LANG_MENU_CASHLESS_PAYMENTS "Безналичные платежи"
	#define LANG_MENU_SETTINGS			"Настройки"
	#define LANG_MENU_INTERNET_SETTINGS	"Интернет"
	#define LANG_MENU_INTERNET_SOURCE	"Тип соединения"
	#define LANG_MENU_MODEM_SETTINGS	"Настр. модема"
	#define LANG_MENU_ETHERNET_SETTINGS	"Настр. Ethernet"
	#define LANG_MENU_TIME_SETTINGS		"Синхронизация времени"
	#define LANG_MENU_TIME_CURRENT		"Текущее время"
	#define LANG_MENU_TIME_SOURCE		"Источник времени"
	#define LANG_MENU_FROM_ECR			"Из кассы"
	#define LANG_MENU_TIMEZONE			"Часовой пояс"
	#define LANG_MENU_DAYLIGHT			"Летнее время"
	#define LANG_MENU_UPDATE_TIME		"Синхр.время сейчас"
	#define LANG_MENU_DISK_EXPLORER		"Проводник"
	#define LANG_MENU_RESET_SETTINGS	"Сброс настроек"
	#define LANG_MENU_INFO				"Инфо"
	#define LANG_MENU_CHANGE_USER		"Сменить пользователя"
	#define LANG_MENU_CHANGE_MY_PASSW	"Изменить пароль"
	#define	LANG_MENU_GOODS_ORDER		"Заказ товаров"
	#define	LANG_MENU_GOODS_NUMBER		"Номер товара"
	#define	LANG_MENU_GOODS_QUANTITY	"Колличество"
	#define LANG_MENU_GOODS_NAME		"Товар"
	#define LANG_MENU_GOODS_PRICE		"Цена"
	#define LANG_MENU_GOODS_SEND_ORDER	"Отсылать заказ?"
	#define LANG_MENU_CHOOSE_COUNTRY	"Выберите страну"
	#define LANG_MENU_CHOOSE_PROVIDER	"Выберите провайдера"
	#define LANG_MENU_APN_PROFILES		"Профили"
	#define LANG_MENU_MANUAL_SETTING	"Вручную"
	#define LANG_MENU_GPRS_SETTINGS		"Настройка GPRS"
	#define LANG_MENU_CHOOSE_SIMCARD	"Выбор SIM-карты"
	#define LANG_MENU_CURRENT_SIMCARD	"Текущая SIM"
	#define LANG_MENU_CHECK_BALANCE		"Счёт SIM-карты"
	#define LANG_MENU_INCOMING_CALL		"Входящий звонок"
	#define LANG_MENU_REJECT_CALL		"не принимать"
	#define LANG_MENU_ANSWER_CALL		"автоприём"
	#define LANG_MENU_ASK_CALL			"вручную"
	#define LANG_MENU_ROAMING			"Роуминг"
	#define LANG_MENU_ROAMING_DISABLED	"запрещёно"
	#define LANG_MENU_ROAMING_ENABLED	"разр.роуминг"
	#define LANG_MENU_ROAMING_NATIONAL	"национал.роуминг"
	#define LANG_MENU_MAKE_A_CALL		"Тестовый звонок"
	#define LANG_MENU_USSD_REQUEST		"USSD-запрос"
	#define LANG_MENU_VERSION			"Версия"
	#define LANG_MENU_STATISTICS		"Статистика"
	#define LANG_MENU_TASKS				"Задачи"
	#define LANG_MENU_AUTO				"Автоматически"
	#define LANG_MENU_GPRS_MODEM		"GPRS"
	#define LANG_MENU_TESTS				"Тесты"
	#define LANG_MENU_TEST_DATAFLASH	"Тест FLASH памяти"
	#define LANG_MENU_TEST_SDCARD		"Тест SD-карты"
	#define LANG_MENU_TEST_RS232		"Тест COM-порт"
	#define LANG_MENU_TEST_EXT_MAGN		"Тест счит.магн.карт"
	#define LANG_MENU_TEST_INT_MAGN		"Тест счит.магн.карт"
	#define LANG_MENU_TEST_INT_SMART	"Тест смарт.карт.счит"
	#define LANG_MENU_TEST_INT_SMART	"Тест cчит.SMART-карт"
	#define LANG_MENU_TEST_RFID			"Тест RFID-считывателя"
	#define LANG_MENU_TEST_RFID_CARD	"Test RFID-CARD"
	#define LANG_MENU_TEST_SOUND		"Тест звука"
	#define LANG_MENU_TEST_MODEM		"Тест модема"
	#define LANG_MENU_TEST_INTERNET		"Тест Internet"
	#define LANG_MENU_TEST_ETHERNET		"Тест Ethernet"
	#define LANG_MENU_TEST_USB			"Тест USB"
	#define LANG_MENU_TEST_QR			"Тест QR кода"
	#define LANG_MENU_APP_SETTINGS		"Настр.приложений"
	#define LANG_MENU_UPDATE_FW			"Обновление ПО"
	#define LANG_MENU_UPDATE_FW_OPTIONS	"Настр. обновлений"
	#define LANG_MENU_UPDATE_FW_NOW		"Обновить сейчас"
	#define LANG_MENU_TS_KEY			"Клавиша \"ПС\""
	#define LANG_MENU_CHANGE_TS_KEY_FN	"Поменять функции клавиш \"ПС\" и \"АН\""
	#define LANG_MENU_MENUBTN_REACTION	"Переход в кассу"
	#define LANG_MENU_MENUBTN_TO_ECR	"переходить"
	#define LANG_MENU_MENUBTN_ASK		"спросить"
	#define LANG_MENU_MENUBTN_IGNORE	"не переходить"
	#define LANG_MENU_USE_FEATURE		"Использовать"
	#define LANG_MENU_NOT_USE_FEATURE	"Не использовать"
	#define LANG_MENU_CHECK_CONNECTION	"Проверка связи"
	#define LANG_MENU_DEVICES			"Устройства и периферия"
	#define LANG_MENU_EXTERNAL_PORT		"COM 1"
	#define LANG_MENU_MAGN_READER		"Счит.магн.карт"
	#define LANG_MENU_CSD				"Порт CSD-модема"
	#define LANG_MENU_ADVANCED			"Дополнительно"
	#define LANG_MENU_FILE_SYSTEM		"Работа с файлами"
	#define LANG_MENU_FORMAT_DF			"Форматирование"
	#define LANG_MENU_FOLDER_IS_EMPTY	"Папка пуста"
	#define LANG_MENU_FORM_IS_EMPTY		"Форма пуста"
	#define LANG_MENU_INITIALIZATION	"Инициализация"
	#define LANG_MENU_DEVICE_NAME		"Имя уст-ва"
	#define LANG_MENU_ACTIVITY			"Активность"
	#define LANG_MENU_ENTER_AMOUNT 		"Введите сумму:"
	#define	LANG_MENU_MESSAGE_QR_HARDWARE_TEST "Введите текст (до 227 симв.):"
	#define LANG_MENU_MESSAGE_MAGN_HARDWARE_TEST "Ожидание карты..."
	#define LANG_MENU_MESSAGE_MAGN_HARDWARE_TEST_RESULT "Тест считывателя магнитной карты..."
	#define LANG_MENU_MESSAGE_INTERNET_HARDWARE_TEST "Идет процесс тестирования..."
	#define LANG_MENU_MESSAGE_INTERNET_TEST_RESULT "Тест Internet"
	#define LANG_MENU_MESSAGE_WAIT_INTERNET_TEST "Waiting test closed"
	#define LANG_MENU_MESSAGE_ETHERNET_HARDWARE_TEST "Подключите Ethernet кабель!"
	#define LANG_MENU_MESSAGE_ETHERNET_TEST_RESULT "Test Ethernet"
	#define LANG_MENU_MESSAGE_COM_HARDWARE_TEST "Встановіть заглушку в СОМпорт!"
	#define LANG_MENU_MESSAGE_COM_TEST_RESULT "Тест СОМпорт"
	#define LANG_MENU_MESSAGE_COM_TEST_RESULT_NOT_PORT "ERROR: COM порт недоступен"
	#define LANG_MENU_MESSAGE_SURFACE_HARDWARE_TEST "Идет процесс тестирования..."
	#define LANG_MENU_MESSAGE_FLASH_TEST_RESULT "Тест FLASH памяти"
	#define LANG_MENU_MESSAGE_SD_TEST_RESULT "Тест SD карты"
	#define LANG_MENU_MESSAGE_GSM_MODEM_HARDWARE_TEST "Идет процесс тестирования..."
	#define LANG_MENU_MESSAGE_GSM_MODEM__TEST_RESULT "Тест модема"
	#define LANG_MENU_MESSAGE_RFID_CARD_HARDWARE_TEST "Ожидание карты..."
	#define LANG_MENU_MESSAGE_RFID_CARD_TEST_RESULT "Тест считывателя RFIDкарты"
	#define LANG_ERROR_NO_DISK			"Диск не найден"
	#define LANG_ERROR_DISK_IO			"Ошибка диска"
	#define LANG_ERROR_MEMORY			"Недостаточно памяти"
	#define LANG_ERROR_BUFFER_OVERFLOW	"Переполнение буфера"
	#define LANG_ERROR_TIMEOUT			"Таймаут"
	#define LANG_ERROR_CANCELED			"Отменено"
	#define LANG_PLUG_IN_ETHERNET	    "Подключите Ethernet кабель"

#elif UNS_LANGUAGE == UNS_LANGUAGE_UKRAINIAN

	#define LANG_STD_FORM_YES			"Так"
	#define LANG_STD_FORM_NO			"Ні"
	#define LANG_STD_FORM_RETRY			"Знову"
	#define LANG_STD_FORM_ABORT			"Відмінити"
	#define LANG_STD_FORM_IGNORE		"Ігнорувати"

	#define LANG_MENU_BUTTON_BACK		"Назад"
	#define LANG_MENU_BUTTON_NEXT		"Далi"	//Сальвадор
	#define LANG_MENU_BUTTON_CANCEL		"Вiдм."
	#define LANG_MENU_BUTTON_OK			" OK "
	#define LANG_MENU_BUTTON_YES		" Так "
	#define LANG_MENU_BUTTON_NO			" Нi "
	#define LANG_MENU_BUTTON_PRINT		"Друк"
	#define LANG_MENU_BUTTON_STATS		"Стат."
	#define LANG_MENU_BUTTON_CHOOSE		"Вибiр"
	#define LANG_MENU_BUTTON_STOP		"Стоп"
	#define LANG_MENU_BUTTON_HANG_UP	"Сброс"	//????
	#define LANG_MENU_BUTTON_ANSWER		"Вiдп."
	#define LANG_MENU_BUTTON_EXIT		"Вихід"
	#define LANG_MENU_BUTTON_OPTIONS	"Опції"

	#define LANG_MENU_BOOK_SETTINGS		"ГОЛОВНЕ МЕНЮ"
	#define LANG_MENU_CASHLESS_PAYMENTS "Безготівкові платежі"
	#define LANG_MENU_SETTINGS			"Налаштування"
	#define LANG_MENU_INTERNET_SETTINGS	"Iнтернет"
	#define LANG_MENU_INTERNET_SOURCE	"Тип з'єднання"
	#define LANG_MENU_MODEM_SETTINGS	"Налашт. модема"
	#define LANG_MENU_ETHERNET_SETTINGS	"Налашт. Ethernet"
	#define LANG_MENU_TIME_SETTINGS		"Cинхронiзацiя часу"
	#define LANG_MENU_TIME_CURRENT		"Поточний час"
	#define LANG_MENU_TIME_SOURCE		"Джерело часу"
	#define LANG_MENU_FROM_ECR			"З каси"
	#define LANG_MENU_TIMEZONE			"Часовий пояс"
	#define LANG_MENU_DAYLIGHT			"Лiтнiй час"
	#define LANG_MENU_UPDATE_TIME		"Синхр.час зараз"
	#define LANG_MENU_DISK_EXPLORER		"Провiдник"
	#define LANG_MENU_RESET_SETTINGS	"Скидання налаштувань"
	#define LANG_MENU_INFO				"Iнфо"
	#define LANG_MENU_CHANGE_USER		"Змiнити користувача"
	#define LANG_MENU_CHANGE_MY_PASSW	"Змiнити пароль"
	#define	LANG_MENU_GOODS_ORDER		"Замовлення товарів"
	#define	LANG_MENU_GOODS_NUMBER		"Код товару"
	#define	LANG_MENU_GOODS_QUANTITY	"Кількість"
	#define LANG_MENU_GOODS_NAME		"Товар"
	#define LANG_MENU_GOODS_PRICE		"Ціна"
	#define LANG_MENU_GOODS_SEND_ORDER	"Відсилати замовлення?"
	#define LANG_MENU_CHOOSE_COUNTRY	"Оберiть країну"
	#define LANG_MENU_CHOOSE_PROVIDER	"Оберiть провайдера"
	#define LANG_MENU_APN_PROFILES		"Профiлi"
	#define LANG_MENU_MANUAL_SETTING	"Вручну"
	#define LANG_MENU_GPRS_SETTINGS		"Налашт. GPRS"
	#define LANG_MENU_CHOOSE_SIMCARD	"Вибiр SIM-карти"
	#define LANG_MENU_CURRENT_SIMCARD	"Поточна SIM"
	#define LANG_MENU_CHECK_BALANCE		"Рахунок SIM-карти"
	#define LANG_MENU_INCOMING_CALL		"Вхiдний виклик"
	#define LANG_MENU_REJECT_CALL		"не приймати"
	#define LANG_MENU_ANSWER_CALL		"автоприйом"
	#define LANG_MENU_ASK_CALL			"вручну"
	#define LANG_MENU_ROAMING			"Роумiнг"
	#define LANG_MENU_ROAMING_DISABLED	"заборона"
	#define LANG_MENU_ROAMING_ENABLED	"дозв.роумiнг"
	#define LANG_MENU_ROAMING_NATIONAL	"нацiонал.роумiнг"
	#define LANG_MENU_MAKE_A_CALL		"Тестовий дзвiнок"
	#define LANG_MENU_USSD_REQUEST		"USSD-запит"
	#define LANG_MENU_VERSION			"Версiя"
	#define LANG_MENU_STATISTICS		"Статистика"
	#define LANG_MENU_TASKS				"Процеси"
	#define LANG_MENU_AUTO				"Автоматично"
	#define LANG_MENU_GPRS_MODEM		"GPRS"
	#define LANG_MENU_TESTS				"Тестування"
	#define LANG_MENU_TEST_DATAFLASH	"Тест FLASH пам'ятi"
	#define LANG_MENU_TEST_SDCARD		"Тест SD-карти"
	#define LANG_MENU_TEST_RS232		"Тест COM-порт"
	#define LANG_MENU_TEST_EXT_MAGN		"Тест зчит.магн.карт"
	#define LANG_MENU_TEST_INT_MAGN		"Тест зчит.магн.карт"
	#define LANG_MENU_TEST_INT_SMART	"Тест зчит.SMART-карт"
	#define LANG_MENU_TEST_RFID			"Тест RFID-зчитувача"
	#define LANG_MENU_TEST_RFID_CARD	"Test RFID-CARD"
	#define LANG_MENU_TEST_SOUND		"Тест звука"
	#define LANG_MENU_TEST_MODEM		"Тест модема"
	#define LANG_MENU_TEST_INTERNET		"Тест Internet"
	#define LANG_MENU_TEST_ETHERNET		"Тест Ethernet"
	#define LANG_MENU_TEST_USB			"Тест USB"
	#define LANG_MENU_TEST_QR			"Тест QR коду"
	#define LANG_MENU_APP_SETTINGS		"Налашт.застосунків"
	#define LANG_MENU_UPDATE_FW			"Оновлення ПЗ"
	#define LANG_MENU_UPDATE_FW_OPTIONS	"Налашт. оновлення"
	#define LANG_MENU_UPDATE_FW_NOW		"Оновити зараз"
	#define LANG_MENU_TS_KEY			"Клавіша \"ПС\""
	#define LANG_MENU_CHANGE_TS_KEY_FN	"Змінити місцями функції клавіш \"ПС\" та \"АН\""
	#define LANG_MENU_MENUBTN_REACTION	"Перехід в касу"
	#define LANG_MENU_MENUBTN_TO_ECR	"переходити"
	#define LANG_MENU_MENUBTN_ASK		"спитати"
	#define LANG_MENU_MENUBTN_IGNORE	"не переходити"
	#define LANG_MENU_USE_FEATURE		"Використовувати"
	#define LANG_MENU_NOT_USE_FEATURE	"Не використовувати"
	#define LANG_MENU_CHECK_CONNECTION	"Перевiрка зв'язку"
	#define LANG_MENU_DEVICES			"Пристрої та периферія"
	#define LANG_MENU_EXTERNAL_PORT		"COM 1"
	#define LANG_MENU_MAGN_READER		"Зчит.магн.карт"
	#define LANG_MENU_CSD				"Порт CSD-модему"
	#define LANG_MENU_ADVANCED			"Додатково"
	#define LANG_MENU_FILE_SYSTEM		"Робота з файлами"
	#define LANG_MENU_FORMAT_DF			"Форматування"
	#define LANG_MENU_FOLDER_IS_EMPTY	"Папка порожня"
	#define LANG_MENU_FORM_IS_EMPTY		"Форма порожня"
	#define LANG_MENU_INITIALIZATION	"Iніціалізація"
	#define LANG_MENU_DEVICE_NAME		"Iм'я пристрою"
	#define LANG_MENU_ACTIVITY			"Активнiсть"
	#define LANG_MENU_ENTER_AMOUNT 		"Введіть суму:"
	#define	LANG_MENU_MESSAGE_QR_HARDWARE_TEST "Введіть текст:"
	#define LANG_MENU_MESSAGE_MAGN_HARDWARE_TEST "Очікування карти..."
	#define LANG_MENU_MESSAGE_MAGN_HARDWARE_TEST_RESULT "Тест зчитування магнітної карти"
	#define LANG_MENU_MESSAGE_INTERNET_HARDWARE_TEST "Відбувається процес тестування..."
	#define LANG_MENU_MESSAGE_INTERNET_TEST_RESULT "Тест Internet"
	#define LANG_MENU_MESSAGE_WAIT_INTERNET_TEST "Waiting test closed"
	#define LANG_MENU_MESSAGE_ETHERNET_HARDWARE_TEST "Підключіть Ethernet кабель!"
	#define LANG_MENU_MESSAGE_ETHERNET_TEST_RESULT "Test Ethernet"
	#define LANG_MENU_MESSAGE_COM_HARDWARE_TEST "Встановіть заглушку в СОМпорт!"
	#define LANG_MENU_MESSAGE_COM_TEST_RESULT "Тест СОМпорт"
	#define LANG_MENU_MESSAGE_COM_TEST_RESULT_NOT_PORT "ERROR: Немає доступу до COM порту"
	#define LANG_MENU_MESSAGE_SURFACE_HARDWARE_TEST "Відбувається процес тестування..."
	#define LANG_MENU_MESSAGE_FLASH_TEST_RESULT "Тест FLASH пам'яті"
	#define LANG_MENU_MESSAGE_SD_TEST_RESULT "Тест SD картки"
	#define LANG_MENU_MESSAGE_GSM_MODEM_HARDWARE_TEST "Відбувається процес тестування..."
	#define LANG_MENU_MESSAGE_GSM_MODEM__TEST_RESULT "Тест модема"
	#define LANG_MENU_MESSAGE_SMART_CARD_HARDWARE_TEST "Очікування карти..."
	#define LANG_MENU_MESSAGE_SMART_CARD_TEST_RESULT "Тест зчитування SMART карти"
	#define LANG_MENU_MESSAGE_RFID_CARD_HARDWARE_TEST "Очікування карти..."
	#define LANG_MENU_MESSAGE_RFID_CARD_TEST_RESULT "Тест зчитування RFIDкарти"
	#define LANG_ERROR_NO_DISK			"Диск не знайдено"
	#define LANG_ERROR_DISK_IO			"Помилка диска"
	#define LANG_ERROR_MEMORY			"Недостатньо пам'ятi"
	#define LANG_ERROR_BUFFER_OVERFLOW	"Переповнення буфера"
	#define LANG_ERROR_TIMEOUT			"Таймаут"
	#define LANG_ERROR_CANCELED			"Вiдмiнено"
	#define LANG_PLUG_IN_ETHERNET	    "Підключіть Ethernet кабель"

#else
	#define LANG_STD_FORM_YES			"Yes"
	#define LANG_STD_FORM_NO			"No"
	#define LANG_STD_FORM_RETRY			"Retry"
	#define LANG_STD_FORM_ABORT			"Abort"
	#define LANG_STD_FORM_IGNORE		"Ignore"

	#define LANG_MENU_BUTTON_BACK		"Back"
	#define LANG_MENU_BUTTON_NEXT		"Next"
	#define LANG_MENU_BUTTON_CANCEL		"Cancl"	//?
	#define LANG_MENU_BUTTON_OK			" OK "
	#define LANG_MENU_BUTTON_YES		" Yes "
	#define LANG_MENU_BUTTON_NO			" No "
	#define LANG_MENU_BUTTON_PRINT		"Print"
	#define LANG_MENU_BUTTON_STATS		"Stats"
	#define LANG_MENU_BUTTON_CHOOSE		"Chose"	//?
	#define LANG_MENU_BUTTON_STOP		"Stop"
	#define LANG_MENU_BUTTON_HANG_UP	"Hang"
	#define LANG_MENU_BUTTON_ANSWER		"Answr"
	#define LANG_MENU_BUTTON_EXIT		"Exit"
	#define LANG_MENU_BUTTON_OPTIONS	"Optns"
	#define LANG_MENU_BUTTON_HEX		"[HEX]"
	#define LANG_MENU_BUTTON_TXT		"[TXT]"

	#define LANG_MENU_BOOK_SETTINGS		"MAIN MENU"
	#define LANG_MENU_CASHLESS_PAYMENTS "Cashless payments"
	#define LANG_MENU_SETTINGS			"Settings"
	#define LANG_MENU_INTERNET_SETTINGS	"Internet"
	#define LANG_MENU_INTERNET_SOURCE	"Connection type"
	#define LANG_MENU_TIME_SETTINGS		"Time sync"
	#define LANG_MENU_TIME_CURRENT		"Current time"
	#define LANG_MENU_TIME_SOURCE		"Time source"
	#define LANG_MENU_FROM_ECR			"From ECR"
	#define LANG_MENU_TIMEZONE			"Timezone"
	#define LANG_MENU_DAYLIGHT			"Daylight zone"
	#define LANG_MENU_UPDATE_TIME		"Update time"
	#define	LANG_MENU_GOODS_ORDER		"Goods order"
	#define	LANG_MENU_GOODS_NUMBER		"Goods number"
	#define	LANG_MENU_GOODS_QUANTITY	"Quantity"
	#define LANG_MENU_GOODS_NAME		"Goods"
	#define LANG_MENU_GOODS_PRICE		"Price"
	#define LANG_MENU_GOODS_SEND_ORDER	"Send order?"
	#define LANG_MENU_MODEM_SETTINGS	"Modem settings"
	#define LANG_MENU_ETHERNET_SETTINGS	"Ethernet settings"
	#define LANG_MENU_DISK_EXPLORER		"Disk explorer"
	#define LANG_MENU_RESET_SETTINGS	"Restore factory settings"
	#define LANG_MENU_INFO				"Info"
	#define LANG_MENU_CHANGE_USER		"Change user"
	#define LANG_MENU_CHANGE_MY_PASSW	"Change my password"
	#define LANG_MENU_CHOOSE_COUNTRY	"Choose country"
	#define LANG_MENU_CHOOSE_PROVIDER	"Choose provider"
	#define LANG_MENU_APN_PROFILES		"Profiles"
	#define LANG_MENU_MANUAL_SETTING	"Manual settings"
	#define LANG_MENU_GPRS_SETTINGS		"GPRS settings"
	#define LANG_MENU_CHOOSE_SIMCARD	"Choose SIM-card"
	#define LANG_MENU_CURRENT_SIMCARD	"Current SIM"
	#define LANG_MENU_CHECK_BALANCE		"SIM balance"
	#define LANG_MENU_INCOMING_CALL		"Incoming call"
	#define LANG_MENU_REJECT_CALL		"Reject"
	#define LANG_MENU_ANSWER_CALL		"Answer"
	#define LANG_MENU_ASK_CALL			"Ask user"
	#define LANG_MENU_ROAMING			"Roaming"
	#define LANG_MENU_ROAMING_DISABLED	"Disabled"
	#define LANG_MENU_ROAMING_ENABLED	"Enabled"
	#define LANG_MENU_ROAMING_NATIONAL	"National"
	#define LANG_MENU_MAKE_A_CALL		"Make a call"
	#define LANG_MENU_USSD_REQUEST		"USSD request"
	#define LANG_MENU_VERSION			"Version"
	#define LANG_MENU_STATISTICS		"Statistics"
	#define LANG_MENU_TASKS				"Tasks"
	#define LANG_MENU_AUTO				"Auto"
	#define LANG_MENU_GPRS_MODEM		"GPRS"
	#define LANG_MENU_TESTS				"Hardware test"
	#define LANG_MENU_TEST_DATAFLASH	"Test FLASH memory"
	#define LANG_MENU_TEST_SDCARD		"Test SD-card"
	#define LANG_MENU_TEST_RS232		"Test COM-port"
	#define LANG_MENU_TEST_EXT_MAGN		"Test ext.magn.reader"
	#define LANG_MENU_TEST_INT_MAGN		"Test int.magn.reader"
	#define LANG_MENU_TEST_INT_SMART	"Test SMART-card reader"
	#define LANG_MENU_TEST_RFID			"Test RFID-reader"
	#define LANG_MENU_TEST_RFID_CARD	"Test RFID-CARD"
	#define LANG_MENU_TEST_SOUND		"Test sound"
	#define LANG_MENU_TEST_MODEM		"Test GSM-modem"
	#define LANG_MENU_TEST_INTERNET		"Test Internet"
	#define LANG_MENU_TEST_ETHERNET		"Test Ethernet"
	#define LANG_MENU_TEST_USB			"Test USB"
	#define LANG_MENU_TEST_QR			"Test QR code"
	#define LANG_MENU_APP_SETTINGS		"App. settings"
	#define LANG_MENU_UPDATE_FW			"FW update"
	#define LANG_MENU_UPDATE_FW_OPTIONS	"Update settings"
	#define LANG_MENU_UPDATE_FW_NOW		"Check now"
	#define LANG_MENU_TS_KEY			"Key \"ST\""
	#define LANG_MENU_CHANGE_TS_KEY_FN	"Change keys functions \"VOID\" and \"ST\""
	#define LANG_MENU_MENUBTN_REACTION	"Switch to ECR"
	#define LANG_MENU_MENUBTN_TO_ECR	"switch"
	#define LANG_MENU_MENUBTN_ASK		"ask"
	#define LANG_MENU_MENUBTN_IGNORE	"do not switch"
	#define LANG_MENU_USE_FEATURE		"Use"
	#define LANG_MENU_NOT_USE_FEATURE	"Do not use"
	#define LANG_MENU_CHECK_CONNECTION	"Check connection"
	#define LANG_MENU_DEVICES			"Devices"
	#define LANG_MENU_EXTERNAL_PORT		"External port"
	#define LANG_MENU_MAGN_READER		"Magnetic reader"
	#define LANG_MENU_CSD				"CSD-modem"
	#define LANG_MENU_ADVANCED			"Advanced"
	#define LANG_MENU_FILE_SYSTEM		"File system"
	#define LANG_MENU_FORMAT_DF			"Format internal memory"
	#define LANG_MENU_FOLDER_IS_EMPTY	"Folder is empty"
	#define LANG_MENU_FORM_IS_EMPTY		"Form is empty"
	#define LANG_MENU_INITIALIZATION	"Initialization"
	#define LANG_MENU_DEVICE_NAME		"Device name"
	#define LANG_MENU_ACTIVITY			"Activity"
	#define LANG_MENU_ENTER_AMOUNT 		"Enter amount:"
	#define	LANG_MENU_MESSAGE_QR_HARDWARE_TEST "Input text (max 227 chs):"
	#define LANG_MENU_MESSAGE_MAGN_HARDWARE_TEST "Waiting for card..."
	#define LANG_MENU_MESSAGE_MAGN_HARDWARE_TEST_RESULT "Test magnetic card reader"
	#define LANG_MENU_MESSAGE_INTERNET_HARDWARE_TEST "Testing..."
	#define LANG_MENU_MESSAGE_INTERNET_TEST_RESULT "Test Internet"
	#define LANG_MENU_MESSAGE_WAIT_INTERNET_TEST "Waiting test closed"
	#define LANG_MENU_MESSAGE_ETHERNET_HARDWARE_TEST "Plug in Ethernet cable!"
	#define LANG_MENU_MESSAGE_ETHERNET_TEST_RESULT "Test Ethernet"
	#define LANG_MENU_MESSAGE_COM_HARDWARE_TEST "Insert stub into COMport!"
	#define LANG_MENU_MESSAGE_COM_TEST_RESULT "Test COMport"
	#define LANG_MENU_MESSAGE_COM_TEST_RESULT_NOT_PORT "ERROR: COM port is unavailable"
	#define LANG_MENU_MESSAGE_SURFACE_HARDWARE_TEST "Testing.."
	#define LANG_MENU_MESSAGE_FLASH_TEST_RESULT "Test FLASH memory"
	#define LANG_MENU_MESSAGE_SD_TEST_RESULT "Test SD card"
	#define LANG_MENU_MESSAGE_GSM_MODEM_HARDWARE_TEST "Testing.."
	#define LANG_MENU_MESSAGE_GSM_MODEM__TEST_RESULT "Test modem"
	#define LANG_MENU_MESSAGE_SMART_CARD_HARDWARE_TEST "Waiting for card..."
	#define LANG_MENU_MESSAGE_SMART_CARD_TEST_RESULT "Test SMART card reader"
	#define LANG_MENU_MESSAGE_RFID_CARD_HARDWARE_TEST "Waiting for card..."
	#define LANG_MENU_MESSAGE_RFID_CARD_TEST_RESULT "Test RFID card reader"
	#define LANG_ERROR_NO_DISK			"No disk found"
	#define LANG_ERROR_DISK_IO			"Disk error"
	#define LANG_ERROR_MEMORY			"Not enough memory"
	#define LANG_ERROR_BUFFER_OVERFLOW	"Buffer overflow"
	#define LANG_ERROR_TIMEOUT			"Timeout"
	#define LANG_ERROR_CANCELED			"Canceled"
	#define LANG_PLUG_IN_ETHERNET	    "Please plug in Ethernet cable"

#endif

#define LANG_MENU_BUTTON_OK				" OK "

#endif /* LOCALIZATION_MENU_H_ */
